### ISSUE TITLE
thicken does not work on directly imported STL

### ISSUE THREAD

**Issue by donaldlee2008** [jimy-byerley/pymadcad#17]
from madcad import *
from madcad.io import *
from madcad.generation import *
print("runing here ")
surface=read("data/aa.stl")
print("runing here 0")
surface = thicken(surface,0.1 ,0.5) 
print("runing here 1")
write(surface, 'data/A12.stl')
print("runing here 2")
show([surface])

>python thickentest.py
  runing here
  runing here 0

that mean I can't run thicken(surface,0.1 ,0.5) .
the  STL file is fine. I can open it on other software

**Comment by donaldlee2008** [comment]
inflateoffsets, inflate have the same problem

**Comment by donaldlee2008** [comment]
there is no any error or warning. just no result

**Comment by jimy-byerley** [comment]
Can you please format the code you post ? It's hard to read without a monospaced font,with no tabs nor colors.
Can you also post a `.stl` file having this issue ? so I could try to reproduce the issue.  `inflate` always worked in my use cases.

**Comment by donaldlee2008** [comment]
please see file attached. code and stl file
[code_and_data.zip](https://github.com/jimy-byerley/pymadcad/files/7849925/code_and_data.zip)

**Comment by jimy-byerley** [comment]
Hello, the probleme is pretty simple in fact:  

- first thing first, your model is of size `1000`, so inflating/thickening of `0.1` doesn't make a big difference ;)

    ```python
    show([ surface, note_bounds(surface) ])
    ```
 
    ![image](https://user-images.githubusercontent.com/7940753/149218661-cca4b9ef-46ab-4b94-b2cf-72640f45b345.png)

-  `inflate` works by moving points along their normal. But a `.stl` file only gives separated triangles (no information about which  triangle is connected to which). Thus the points are moved separately and the triangles get floating apart from each others.

    ```python 
    surface = read('data/aa.stl')
    inflated = inflate(surface, 5)

    show([surface], options={'display_groups': False})
    ```
    
    ![image](https://user-images.githubusercontent.com/7940753/149219404-5b48f08b-cf9c-40f9-bfd7-eee8b8f1be92.png)


   To make the triangles connected, you can just merge the points that are close enough

   ```python 
    surface = read('data/aa.stl')
    surface.mergeclose()
    inflated = inflate(surface, 5)

    show([surface], options={'display_groups': False})
    ```

    ![image](https://user-images.githubusercontent.com/7940753/149219478-e681fb55-e984-458e-90e1-c04dbfec6810.png)


Note that the edges visible on the mesh in the first picture of the image are surface contours. Because by default, edges between adjacent triangles are not displayed (for convenience). So you can easily check when one imported mesh has badly connected components.
