### ISSUE TITLE
Boolean Operations Through Meshes

### ISSUE THREAD

**Issue by charlotte10170** [jimy-byerley/pymadcad#4]
Hi,
I've been trying to compute boolean operations between two meshes, one of which has been imported from outside and read by "madcad.read" command and the other one generated through the "madcad.brick" , but I got this type of error: "Process finished with exit code -1073741819 (0xC0000005)".  
Does anyone have any suggestions on how to cope with this problem?
Thanks a lot in advance

**Comment by jimy-byerley** [comment]
Hello and welcome !

Not sure yet with so few details. 
The output `Process finished with exit code -1073741819 (0xC0000005)` makes me think of a memory corruption due to some compiled code :thinking:  It can be due to 2 different things:  some functions of `madcad.core` used in the boolean operations, or to the display functions (the Qt library)

To decide which of the 2, can you check if the error happens during the boolean operation or during display ?

Can you share more details about what you are trying to do ?
- a piece of code, and the initial imported mesh
- do you use madcad from pypi (currently 0.7)  or the last repository version ? 
- which  OS ?

**Comment by charlotte10170** [comment]
Hi, sorry for the delay in answering you, but, in the meantime, I've installed the last repository version of pymadcad and made other trials in order to compute the same boolean difference between an imported mesh and a cutting plane.
For better understanding, I attach the image of the intersection between the mesh and the cutting plane, and the final result of the boolean difference.  
![plane and mesh](https://user-images.githubusercontent.com/79510873/124278561-b1ac8800-db46-11eb-86b5-8d186374cb4b.jpeg) 
![boolean result](https://user-images.githubusercontent.com/79510873/124278582-b8d39600-db46-11eb-9c3b-eb7de2295ce5.jpeg)

As you can notice, the function returns only the limited region affected by the presence of the cutting plane, maybe the triangles undergoing a change during the boolean operation, excluding all the rest. 
Do you have any suggestions on how to avoid this error? 
Thanks a lot  in advance for the help you can provide me

**Comment by charlotte10170** [comment]
Hi jimmy-byerley, I am writing to inform you that, finally, I was capable to solve the problem. In particular, it related to the imported mesh which evidently had some irregularities, perhaps due to the import phase. I proceeded, therefore, to fix it by using the "madcad.finish ()" function, through which it was possible to implement the Boolean difference without the problems described above. 
I apologize for the inconvenience but thanks anyway for your prompt reply

**Comment by jimy-byerley** [comment]
Oh well ! I'm glad to know that this was not a bug in the end :)
I suppose the imported mesh had some overlapping geometries, and that  calling `Mesh.mergeclose()` in  method `Mesh.finish` did fixed it.

You're welcome for any other question :+1:
