### ISSUE TITLE
Thicken for a free-form mesh from stl file

### ISSUE THREAD

**Issue by 1939938853** [jimy-byerley/pymadcad#95]
Hi,

I tried to do the `thicken()` operation with a free-form mesh stored in a stl file. It seems not working. Any suggestions?

Thanks

Here is my code
```
from madcad import *
from madcad.generation import *
mesh = read("mesh.stl")
mesh.mergeclose()
thickness = 4
thicken_mesh = thicken(mesh, thickness, 0.5)
show([thicken_mesh])
```
Mesh before `thicken()`
![image](https://github.com/jimy-byerley/pymadcad/assets/59957922/a784eac0-268e-4cd6-b6ba-8902b9fca0a3)

Mesh after `thicken()`
![image](https://github.com/jimy-byerley/pymadcad/assets/59957922/632dbccd-ca65-4e5d-8515-245942084209)
The zipped stl mesh file

[mesh.zip](https://github.com/jimy-byerley/pymadcad/files/12837276/mesh.zip)

**Comment by jimy-byerley** [comment]
Hello
This looks like a wrong thickness was computed for some points of your meshes, this can happen when the input meshes contains geometry artifacts like it is in your case.

Here is your input mesh
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/49cf4969-49ef-47e6-8796-6682778ebde6)
Below is a zoom on the artifact at the bottom of previous image
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/047f50fc-905c-43e7-99e5-1f7a5e9e4d93)

You can see that there is two triangles with 360° angle between them, which makes of it a paradoxical surface.
The wrong result is predictable:
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/c96e5a18-1f87-4b42-8dad-44b4d183b1d9)

If you fix that meshing artifact on your input mesh, your issue is solved

**Comment by 1939938853** [comment]
Thank you Jimy,

Below is the original mesh. Do you mean the triangle marked green has  360° angle with the triangle marked blue? How to judge this is 360° angle and not 0°?   I googled the "paradoxical surface", but cannot find a definition. What it is really about? It is true after `mesh.mergeclose()`, this part looks quite different.

![image](https://github.com/jimy-byerley/pymadcad/assets/59957922/4e2eff79-0db7-4d45-8cc4-47150db70224)

**Comment by jimy-byerley** [comment]
Yes I meant the green and the blue triangles are overlapping with opposite outward directions. 

In fact 0° is the same as 360° speaking of an orientation, in this case the vertex offset computed then tends to $\pm \infty$ because it cannot decide which side is interior and which is exterior.

I do not find a place defining what I called a paradoxical surface either, but let say that it is a surface going through itself, like a [Klein bottle](https://en.wikipedia.org/wiki/Klein_bottle)

**Comment by jimy-byerley** [comment]
Im looking closely to your mesh, and I realize I was wrong, this is not a 360° problem at the position I pointed but a [winding](https://en.wikipedia.org/wiki/Winding_number) consistency issue in your triangles ... how did you generated this mesh, this is not very common that 3d softwares export meshes without widing consistency ?
If you flip the widing (the order of points in the triplet) of the blue triangle, then it is fine. 
Without this, the blue triangle is not overlapping with the green triangle, but yet has a normal opposite to the green one. We can see it by the blue triangle being darker than the green one.

![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/97079c42-c87d-48c5-8657-82c6d2a67347)
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/2541a9b6-a528-4d4f-94de-b2ece735fd7c)


recomputing winding consistency worked for the aforementioned position:
```python
mesh = read('/tmp/mesh.stl')
mesh.mergeclose()
mesh.orient()  # correct winding consistency of all triangles
result = thicken(mesh, 0.1)
```

But there is an other place in your mesh where the 360° angle arise
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/c40100fa-d9ae-4efe-9bb1-f9313c06f0c7)
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/66efc86d-c736-40fc-a13d-75fca8aa97f7)

You can see that the triangles are indeed overlapping, it is not exactly 360° but close to it, so the vertex offset is not infinity but still huge:
![image](https://github.com/jimy-byerley/pymadcad/assets/7940753/63d61ab7-d3c0-4796-903a-3fdc23e16bb0)

**Comment by jimy-byerley** [comment]
This topic has been inactive for few months, and since I explained this was not an issue with the thicken function but with the input mesh, I'm gonna close this issue

Feel free to reopen if you have more questions
